name: Release jar and native binary

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build native with Maven
        run: |
          mvn -B -Pnative \
              -Dnative.image.cache=true \
              -Dnative-image.parallelism=4 \
              -DskipTests \
              package
          chmod +x target/ali-open-token
          cd target
          tar zcvf ali-open-token.tar.gz ali-open-token
          ls -lh

      - name: Create release and upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/ali-open-token-1.0.0.jar
            target/ali-open-token.tar.gz
